name: CI - Testes Unitários (Jest)

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências (sem lockfile)
        run: npm install --no-package-lock

      - name: Rodar testes unitários
        run: npm test
