name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # vai rodar quando a branch main receber mudanças

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload dos arquivos do site
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./  # Se o HTML final estiver em outra pasta, mude aqui

      - name: Publicar no GitHub Pages
        uses: actions/deploy-pages@v4
