name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate-html:
    name: Validar HTML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Criar .git falso se não existir
        run: |
          if [ ! -d ".git" ]; then
            git init
            git config user.email "action@github.com"
            git config user.name "GitHub Action"
            git add .
            git commit -m "Fake commit para html5validator"
          fi

      - name: Rodar validador HTML5
        uses: Cyb3r-Jak3/html5validator-action@v7.0.0
        with:
          root: ./
          log_level: INFO
          css: true
          format: json

  deploy:
    name: Deploy para GitHub Pages
    needs: validate-html
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Montar pasta dist
        run: |
          mkdir dist
          shopt -s extglob
          cp -r !(dist) dist/

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
