name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Python e html5validator
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install html5validator

      - name: Validar HTML5
        run: |
          html5validator --root . --log-level INFO --format json --show-warnings --css

      - name: Preparar pasta dist
        run: |
          mkdir dist
          shopt -s extglob
          cp -r !(dist) dist/

      - name: Upload do build como artefato
        uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Baixar artefato do build
        uses: actions/download-artifact@v4
        with:
          name: site-build
          path: dist

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
