name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure Git is initialized
        run: |
          git init
          git remote remove origin || true
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch origin
          git checkout ${{ github.ref_name }}

      - name: Build project
        run: |
          echo "Nenhum build específico configurado"
          mkdir -p dist
          cp -r * dist/

  validate-html:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action@v7.0.0
        with:
          root: ./dist
          log_level: INFO

  deploy:
    runs-on: ubuntu-latest
    needs: validate-html
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
