name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Ensure Git is initialized
        run: |
          git init
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch origin
          git checkout ${{ github.ref_name }}

      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action@v7.0.0
        with:
          root: ./
          log_level: INFO
          css: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
