name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare HTML files
        run: |
          mkdir -p validated
          cp -r *.html validated/ || true
          cp -r css validated/ || true

      - name: Validate HTML without Git detection
        uses: Cyb3r-Jak3/html5validator-action@v7.0.0
        with:
          root: validated
          log_level: INFO
          format: json
          css: true

      - name: Build project
        run: |
          echo "Nenhum build específico configurado"
          mkdir -p dist
          shopt -s extglob
          cp -r !(dist) dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
